### ISSUE TITLE
Support view-less Elements

### ISSUE THREAD

**Issue by joshaber** [joshaber/Few.swift#31]
Currently there's a 1-to-1 correspondence between `Element`s and views. But that doesn't necessarily have to be the case. A lot of `Element`s exist in the hierarchy for layout reasons only. They don't actually need to exist as reified views.

My current thinking is that `Element` shouldn't create a view but be used only for layout.

**Comment by mrjjwright** [comment]
Yes this I think is quite important and is seen in React, React Native, and Components to keep mounted hierarchies flat.

**Comment by joshaber** [comment]
Yup, I agree. I had this working a while back but removed it because it made the implementation more complex. Probably time to bring it back.
