### ISSUE TITLE
[RFC] Use ComponentSpec as api for defining components

### ISSUE THREAD

**Issue by coenert** [joshaber/Few.swift#40]
Because Swift currently does not support non-generic subclasses, i thought about creating components by implementing a `ComponentSpec` or `ComponentType` protocol. We can use associated types to infer the state type. We only need to know when the state changes, maybe we can make a `State` type that you can observe.

After implementing `ComponentSpec` you can use the method `construct` to create a `Component<Spec.StateType>`

To receive lifecycle events we could add an `LifeCycleEvent` enum, and add `lifeCycleStateChanged(event: LifeCycleEvent)` for receiving those events.

**Comment by joshaber** [comment]
Interesting! So it might look something like:

```swift
protocol ComponentType {
   typealias StateType
   
   func lifeCycleStateChanged(event: LifeCycleEvent)
   func render() -> Element
   
   var stateChanged: () -> ()
}
```

My initial thought is that it doesn't seem to provide much that we don't already get with `Component`s initializers like `Component(initialState:, didRealize:, render:)`.

**Comment by joshaber** [comment]
(I'm also hoping that sooner than later Apple fixes the non-generic subclass problems :cry:.)

**Comment by mrjjwright** [comment]
Can somebody please explain the non-generic subclass problem that is mentioned in the README a bit more.  I don't understand the exact limitation for the design of Few and what has been done to go around it.  We can't subclass Components but the approach shown in the demos seems elegant to me, perhaps I am missing something.

**Comment by joshaber** [comment]
You *can* subclass `Component` but if you override `render` (or probably other functions that take in the state) it'll crash. Currently there are two workarounds:

1. Don't subclass. Use `Component(initialState:, didRealize:, render:)` instead.
2. Subclass, but don't override `render`: https://github.com/joshaber/Few.swift/blob/e4d96d944f6b87e3f02f60cc22fb6db6df76b62f/FewDemo/CustomButton.swift

**Comment by joshaber** [comment]
In light of #44 I think custom components are a bit less onerous. I'm happy to reconsider if I've misunderstood, though!
