### ISSUE TITLE
Nesting and flexbox

### ISSUE THREAD

**Issue by mrjjwright** [joshaber/Few.swift#41]
If I create a root app component with 2 child components, those components flexbox layouts are computed first as independent flexbox layout calls and not as children of the app component's layout. In my case that means they receive no width.  If instead I wrap them in Elements that are children of the app component it works as expected.   Is this by design?  Do I need to create wrapping elements around components to handle certain layout cases?

**Comment by joshaber** [comment]
It *shouldn't* be necessary to wrap them in elements. Could you provide an example where this happens?

**Comment by mrjjwright** [comment]
I am sure I am doing something stupid.

https://gist.github.com/mrjjwright/115abe0bf6e1ec9239a2 <https://gist.github.com/mrjjwright/115abe0bf6e1ec9239a2>

**Comment by joshaber** [comment]
Definitely a bug. We currently copy the layout properties from the component to the root element: https://github.com/joshaber/Few.swift/blob/e4d96d944f6b87e3f02f60cc22fb6db6df76b62f/FewCore/Component.swift#L99

In this case that overwrites the assigned `flex`. I imagine we should only copy those attributes which have been set.

**Comment by joshaber** [comment]
>Or perhaps don't copy them at all?

This. Components should set their own styles. If they want an outside user to set something, they should take it as an arg.

**Comment by mrjjwright** [comment]
Yeah that copying code looked suspect to me as well.  I tried commenting it out yesterday before I submitted the bug I thought but perhaps I didn't get it quite right.
