### ISSUE TITLE
How to have overlapping elements?

### ISSUE THREAD

**Issue by adly-holler** [joshaber/Few.swift#67]
Hi, I'm trying to create a cell that looks like

![few-layered-cell-example](https://cloud.githubusercontent.com/assets/2466893/7667961/df3d75d4-fbd4-11e4-81de-72f72b7e9624.png)

and I need some help getting the small circle into position. Could someone point me in the right direction?

**Comment by adly-holler** [comment]
Help me @joshaber, you're my only hope🔰

**Comment by joshaber** [comment]
Sorry, I've been out of town! Try using a negative margin or padding. I'll try recreating that tomorrow.

**Comment by joshaber** [comment]
Yup, a negative margin will do the right thing. Here's a rough version of that layout:

```swift
Element()
	.direction(.Column)
	.justification(.Center)
	.children([
		Element().height(90).children([
			View(backgroundColor: .grayColor()).width(32),
			View(backgroundColor: .blackColor(), cornerRadius: 20).width(40).height(40).margin(Edges(left: -10)).selfAlignment(.Center),
			Element().selfAlignment(.Center).direction(.Column).flex(1).children([
				Label("Lorem Ipsum"),
				Label("Dolor"),
			]),
			View(backgroundColor: .blackColor()).width(30).height(30).selfAlignment(.Center).margin(Edges(right: 10))
		])
	])
```

**Comment by joshaber** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13760/7707624/ab7dda30-fe1e-11e4-937a-355d02679601.jpg)

**Comment by adly-holler** [comment]
Beautiful, thanks.
