### ISSUE TITLE
Installation documentation?

### ISSUE THREAD

**Issue by hmlongco** [joshaber/Few.swift#70]
Some additional documentation on how to download, install, and run the project would be nice. Plus the same on including Few in my own project.

**Comment by joshaber** [comment]
We support Carthage and then all the usual methods for including 3rd party framework apply.

**Comment by hmlongco** [comment]
So basically developers new to Swift who want to easily download and tryout your code are SOL?

Got it.

**Comment by joshaber** [comment]
Well, obviously I wouldn't put it quite like that :stuck_out_tongue_closed_eyes: 

It's more of a general platform question than a Few-specific question. Check out Carthage or CocoaPods, or lookup how to integrate a 3rd party framework manually.
