### ISSUE TITLE
Add instructions in README on how to edit demo

### ISSUE THREAD

**Issue by joshdholtz** [joshaber/Few.swift#81]
Not sure if it has just been a long week but I'm struggling to get the demo iOS project to update rebuild a framework of my changes :grimacing: 

It looks like it is looking for the `Few.framework` in a `build/Debug-iphoneos` directory but that does not exist. I have tried building/running/archiving the framework targets and no frameworks get put there. Is there something I am missing?

**Comment by joshaber** [comment]
Are you trying to rebuild the framework itself, or one of the demo projects?

**Comment by joshdholtz** [comment]
I was working on adding a fun new feature to `Few.Element` and I wanted to test it in the demo project. The demo project looks like it relies on a built `Few.framework` in the `build/Debug-iphoneos` directory. It didn't seem like my change to `Few.Element` was being reflect in the demo app but I may have been an idiot :grimacing: I will double check to make sure I was actually doing things right.

**Comment by joshaber** [comment]
Ah, sorry about that! It looks like it was trying to link to the Carthage-built version before. It should be fine now.

**Comment by joshdholtz** [comment]
Yesssssss, thank you! Expect more PRs from me :blush:
